### ISSUE TITLE
Clone objects with keyboard arrows

### ISSUE THREAD

**Issue by zmeyc** [zmeyc/mapmaker#14]
Use ALT-arrows to clone objects (or destroy objects if opposite direction is chosen).

For example:
H   // press Down

H
H  // press Down

H
H
H   // press Up

H
H
etc

**Comment by zmeyc** [comment]
Done, but need to check why items(rect) doesn't work (had to iterate all map items).

**Comment by tony-karandeev** [comment]
Using `QGraphicsScene::items()` instead of `QGraphicsView::items()` will help. `QGraphicsView::items()` accepts rect specified in viewport coordinates, while targetRect is in scene coordinates.

**Comment by zmeyc** [comment]
Thanks, Tony.

**Comment by zmeyc** [comment]
It works!
